const JobTypes = {
  CONFIRM_S3_OBJECT_USAGE: 'CONFIRM_S3_OBJECT_USAGE',
  DISABLE_S3_OBJECT_USAGE: 'DISABLE_S3_OBJECT_USAGE',
  AUDIT_S3_OBJECT: 'AUDIT_S3_OBJECT',
};

module.exports = {
  JobTypes,
};
