const JobTypes = {
  CONFIRM_S3_OBJECT_USAGE: 'CONFIRM_S3_OBJECT_USAGE',
  DISABLE_S3_OBJECT_USAGE: 'DISABLE_S3_OBJECT_USAGE',
  AUDIT_S3_OBJECT: 'AUDIT_S3_OBJECT',
  LOG_KITCHEN: 'LOG_KITCHEN',
  LOG_ORDER: 'LOG_ORDER',
  PAY_ORDER: 'PAY_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',
  CANCEL_ORDER_PAID_STATUS: 'CANCEL_ORDER_PAID_STATUS',
};

module.exports = {
  JobTypes,
};
